[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "evmc-supply-curves"
version = "0.1"
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    "numpy",
    "pandas<2.2",
    "matplotlib",
    "pyyaml"
]